### ISSUE TITLE
Mod not working

### ISSUE THREAD

**Issue by BoBkiNN** [Keksuccino/Load-My-Resources#6] opened 2022-11-08 09:59 UTC
**Describe the bug**
Resources not loading

**To Reproduce**
1. Install the mod

**Expected behavior**
Before today menu panorama was changed by loading `minecraft` namespace resources to my, but today this is not working

**Basic Informations (please complete the following information):**
 - OS: Windows 10
 - Forge 36.2.34
 - Minecraft Version: 1.16.5
 - Active Mods: https://cdn.discordapp.com/attachments/999465761431113731/1039478822388641812/modlist.txt

**Comment by baooduy** [comment] 2022-11-08 17:43
Somehow mine isnt working today too, i did nothing, 1.19.2
I think mojang did something since the auth server is down for a few hours today

**Comment by Keksuccino** [comment] 2022-11-08 21:23
It was caused by a combination of the CurseForge launcher and an update to the official MC launcher. The launchers are fixed now and everything works again! :)

**Closed by Keksuccino** 2022-11-08 21:23 UTC
Labels: bug
